spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    open-in-view: 'false'
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD:postgres}
    username: ${POSTGRES_USER:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cinema}
    initialize: 'true'
  sql:
    init:
      mode: always
      platform: postgres
ssl: 'true'
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
