name: Java CI with Maven

on:
  push:
    branches: [ "master", "pipelines" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Setup Firefox
      uses: browser-actions/setup-firefox@latest

    - name: Setup gecko driver
      uses: browser-actions/setup-geckodriver@latest

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Start docker compose
      run: docker-compose up -d

    - name: Build with Maven
      run: mvn -B package -DGECKODRIVER_PATH=$(which geckodriver) -DFIREFOX_PATH= --file backend/pom.xml
